name: OpenSSF Scorecard

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1" # toda segunda 06:00 UTC (ajuste se quiser)
  push:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write # necessário para upload de SARIF no Code Scanning
  actions: read

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Run Scorecard
        uses: ossf/scorecard-action@4eaacf0543bb3f2c246792bd56e8cdeffafb205a # v2.4.3
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: false

      - name: Upload SARIF to Code Scanning
        uses: github/codeql-action/upload-sarif@dd903d2e4f5405488e5ef1422510ee31c8b32357 # v3.36.2
        with:
          sarif_file: results.sarif
